"""empty message

Revision ID: 10108877d3c4
Revises: 89ae32a9643b
Create Date: 2021-11-12 16:38:01.363782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10108877d3c4'
down_revision = '89ae32a9643b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'checked_in_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('checked_in_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
