"""empty message

Revision ID: 80e6fea21ec1
Revises: 10108877d3c4
Create Date: 2021-11-13 18:31:07.167173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80e6fea21ec1'
down_revision = '10108877d3c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('checked_out', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'checked_out')
    # ### end Alembic commands ###
