"""empty message

Revision ID: 89ae32a9643b
Revises: ebd17cd0c154
Create Date: 2021-11-12 13:08:38.951330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89ae32a9643b'
down_revision = 'ebd17cd0c154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('checked_in_status', sa.String(), nullable=True))
    op.drop_column('rental', 'videos_checked_out_count')
    op.drop_column('rental', 'available_inventory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('available_inventory', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rental', sa.Column('videos_checked_out_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('rental', 'checked_in_status')
    # ### end Alembic commands ###
