"""empty message

Revision ID: ebd17cd0c154
Revises: b8799b360a59
Create Date: 2021-11-10 16:05:12.693607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebd17cd0c154'
down_revision = 'b8799b360a59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('available_inventory', sa.Integer(), nullable=True))
    op.add_column('rental', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.add_column('rental', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('rental', sa.Column('video_id', sa.Integer(), nullable=False))
    op.add_column('rental', sa.Column('videos_checked_out_count', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rental', 'video', ['video_id'], ['id'])
    op.create_foreign_key(None, 'rental', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rental', type_='foreignkey')
    op.drop_constraint(None, 'rental', type_='foreignkey')
    op.drop_column('rental', 'videos_checked_out_count')
    op.drop_column('rental', 'video_id')
    op.drop_column('rental', 'due_date')
    op.drop_column('rental', 'customer_id')
    op.drop_column('rental', 'available_inventory')
    # ### end Alembic commands ###
